python3 train_officehome_source.py --batch_size 128 --lr 0.001 --save trained_model/source/office-home/Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Art/
python3 train_officehome_source.py --batch_size 128 --lr 0.001 --save trained_model/source/office-home/Clipart_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Clipart/
python3 train_officehome_source.py --batch_size 128 --lr 0.001 --save trained_model/source/office-home/Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Product/
python3 train_officehome_source.py --batch_size 128 --lr 0.001 --save trained_model/source/office-home/Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Real_World/

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Art2Clipart_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Clipart/ --load_weight trained_model/source/office-home/Art_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Art2Clipart --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Clipart/ --load_weight trained_model/target/office-home/Art2Clipart_new_4.pth --load_weight_source trained_model/source/office-home/Art_new_4.pth 

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Art2Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Product/ --load_weight trained_model/source/office-home/Art_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Art2Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Product/ --load_weight trained_model/target/office-home/Art2Product_new_4.pth --load_weight_source trained_model/source/office-home/Art_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Art2Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Real_World/ --load_weight trained_model/source/office-home/Art_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Art2Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Art/ --val_path ./data/office-home/Real_World/ --load_weight trained_model/target/office-home/Art2Real_World_new_4.pth --load_weight_source trained_model/source/office-home/Art_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Clipart2Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Art/ --load_weight trained_model/source/office-home/Clipart_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Clipart2Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Art/ --load_weight trained_model/target/office-home/Clipart2Art_new_4.pth --load_weight_source trained_model/source/office-home/Clipart_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Clipart2Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Product/ --load_weight trained_model/source/office-home/Clipart_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Clipart2Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Product/ --load_weight trained_model/target/office-home/Clipart2Product_new_4.pth --load_weight_source trained_model/source/office-home/Clipart_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Clipart2Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Real_World/ --load_weight trained_model/source/office-home/Clipart_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Clipart2Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Clipart/ --val_path ./data/office-home/Real_World/ --load_weight trained_model/target/office-home/Clipart2Real_World_new_4.pth --load_weight_source trained_model/source/office-home/Clipart_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Product2Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Art/ --load_weight trained_model/source/office-home/Product_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Product2Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Art/ --load_weight trained_model/target/office-home/Product2Art_new_4.pth --load_weight_source trained_model/source/office-home/Product_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Product2Clipart_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Clipart/ --load_weight trained_model/source/office-home/Product_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Product2Clipart_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Clipart/ --load_weight trained_model/target/office-home/Product2Clipart_new_4.pth --load_weight_source trained_model/source/office-home/Product_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Product2Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Real_World/ --load_weight trained_model/source/office-home/Product_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Product2Real_World_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Product/ --val_path ./data/office-home/Real_World/ --load_weight trained_model/target/office-home/Product2Real_World_new_4.pth --load_weight_source trained_model/source/office-home/Product_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Real_World2Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Art/ --load_weight trained_model/source/office-home/Real_World_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Real_World2Art_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Art/ --load_weight trained_model/target/office-home/Real_World2Art_new_4.pth --load_weight_source trained_model/source/office-home/Real_World_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Real_World2Clipart_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Clipart/ --load_weight trained_model/source/office-home/Real_World_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Real_World2Clipart_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Clipart/ --load_weight trained_model/target/office-home/Real_World2Clipart_new_4.pth --load_weight_source trained_model/source/office-home/Real_World_new_4.pth

python3 train_officehome_target.py --batch_size 128 --lr 0.003 --save trained_model/target/office-home/Real_World2Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 3 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Product/ --load_weight trained_model/source/office-home/Real_World_new_4.pth
python3 train_officehome_final.py --ratio 0.5 --alpha 1 --batch_size 128 --lr 0.003 --save trained_model/final/office-home/Real_World2Product_new --resnet 50 --num_gpu 4 --num_classes 65 --epochs 30 --train_path ./data/office-home/Real_World/ --val_path ./data/office-home/Product/ --load_weight trained_model/target/office-home/Real_World2Product_new_4.pth --load_weight_source trained_model/source/office-home/Real_World_new_4.pth

